### ISSUE TITLE
Find your Friends

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/Security_and_FullstackJavascript_Exam#1]
* Selve applicationen
  * Opbygges af componenter, sørg for at holde alle filer så små som muligt for mere overskuelighed - Code Splitting
  * Lav custom componenter som Header, Input, Card osv
  * Brug constants til ting som colors og andre ting der bruges mange steder, så de kun skal ændres ét sted
  * Gør brug af Screens, frem for pop-ups/modals 

__TASKS__
* [x] ![#4ba38c](https://via.placeholder.com/15/4ba38c/000000?text=+) `(Camilla)` Opret de componenter vi på forhånd ved vi skal bruge, samt de constants vi ved vi skal bruge så de er klar og sørg for at begge dele ligger i separate foldere:
    - [x] ![#4ba38c](https://via.placeholder.com/15/4ba38c/000000?text=+) `(Camilla)` Card component
    - [x] ![#4ba38c](https://via.placeholder.com/15/4ba38c/000000?text=+) `(Camilla)` Input component
    - [x] ![#4ba38c](https://via.placeholder.com/15/4ba38c/000000?text=+) `(Camilla)` Header component
* [x] ![#4ba38c](https://via.placeholder.com/15/4ba38c/000000?text=+) `(Camilla)` Opret MapScreen, LoginScreen, ChatScreen og evt. en HomeScreen og sørg for at de ligger i en separat mappe

**For the above tasks, see #6** 

* [x] ![##0000FF](https://via.placeholder.com/15/0000FF/000000?text=+) `(Rúni)` MapScreen holder styr på alt vedrørende map, position, osv. Hvis der skal være en søgefunktion skal der tages stilling til om den evt skal have sin egen screen
  * [x] ![#FFD700](https://via.placeholder.com/15/FFD700/000000?text=+) `(Asger)` Opdatér facade i frontenden til at kunne håndtere geo-location kald, som MapScreen skal bruge
* [x] LoginScreen holder styr på login, både via oauth og via bcrypr - brug evt noget dummy indtil oauth og bcrypt er lavet. 
* [x] ![#FFD700](https://via.placeholder.com/15/FFD700/000000?text=+) `(Asger)` CreateUser screen that allows non OAuth users to create a user.
* [ ] ChatScreen holder styr på alt vedrørende visning og afsendelse af beskeder
* [x] app.js holder kun styr på nødvendige states delt mellem children, samt hviken screen der skal vises, ala: 
![image](https://user-images.githubusercontent.com/35559774/80920301-30553c00-8d6f-11ea-85bc-041d1dfc1cbe.png)
