### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/Security_and_FullstackJavascript_Exam#2]
Backend application bygges op efter samme principper som vores semester projekt "Teamfinder", dog med mere udviklet bcrypt login, rigtig navngivning (ikke noget med gameuser i.e, lad være med bare at kopiere Lars projekt). Så brug den som udgangspunkt for struktur, indhold og opbygning - medtag kun det vi har brug for i dette projekt. 

Gør evt. brug af graphql til endpoints. 

__TASKS__
* [x] UserFacade with  errorhandling
  * User has:
    * Username
    * Password
    * Name
  * [x] Adduser
    * [ ] **Make sure AddUser can be accessed without login**
  * [x] DeleteUser
  * [x] GetUser
  * [x] GetAllUsers
* [x] ![#FFD700](https://via.placeholder.com/15/FFD700/000000?text=+) `(Asger)` Change UserFacade to transfer data to MySQL server instead of MongoDB ( see #13 )
* [x] ![#c034eb](https://via.placeholder.com/15/c034eb/000000?text=+) `(Malte)` Errorhandling via ApiError ( see #17 )
* [x] Login via basic-auth
  * [x] CheckUser and middleware (for bcrypt/basic Auth login)
  * [x] ![#c71c1c](https://via.placeholder.com/15/c71c1c/000000?text=+) `(BUG)` ![#4ba38c](https://via.placeholder.com/15/4ba38c/000000?text=+) `(Camilla)`  Theres an issue with the basic-auth middelware. After login we get this error:
  ![image](https://user-images.githubusercontent.com/35559774/82200023-c6a46880-98fe-11ea-8cae-335cdd9ca9d7.png)
  This was not an error yesterday when the basic auth was implemented. I think the errormessage means that the response is an html-errorpage and not a json response. Through console.logs I've narrowed it down to either the resolvermap.ts or simply something in the basic auth that trickles down. 

* [ ] MapFacade
* [ ] Message/Chat Facade
* [ ] Graphql schema and resolvers
  * [x] Graphql UserFacde-functions
  * [x] GraphQL for positions (MongoDB)
  * [ ] GraphQL for chat messages and chat history (MongoDB) (low priority)
* [x] ![#FFD700](https://via.placeholder.com/15/FFD700/000000?text=+) `(Asger)` Positions ( see #21 )
* [x] ![##0000FF](https://via.placeholder.com/15/0000FF/000000?text=+) `(Rúni)` Logging
* [ ] Chat/message if time

**Comment by MalteMagnussen** [comment]
Vi kan bruge [GraphQL med Apollo](https://www.apollographql.com/) til Backend. Det kunne være cool at demonstrere.

**Comment by MalteMagnussen** [comment]
Vi bruger en Node.js backend, ikke? Tænker at begynde at sætte nogen ting op. 
Lave en "Backend" folder i roden af projektet.

**Comment by MalteMagnussen** [comment]
Der er en tutorial her
Har efterhånden set på en del tutorials, bare for at sammenligne, og et fællestræk, er at man i dem alle skal ind på https://console.developers.google.com/apis/credentials og oprette et nyt projekt og nogen nøgler.

**Comment by MalteMagnussen** [comment]
See #7 for initial Pull Request of Backend

**Comment by MrHardcode** [comment]
![image](https://user-images.githubusercontent.com/44898491/82256398-8ffa3c80-9956-11ea-853c-0e6fb697d609.png)
It should definitely have its own facade. It will be connecting to MongoDB and UserFacade will end up connect to MySQL. I don't think we should mix those up in the same file.
