### ISSUE TITLE
Oauth

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/Security_and_FullstackJavascript_Exam#3]
Find ud af hvordan vi bruger Oauth og SSO og færdiggør derefter denne userstory!   
  
## Tasks
* [x] Learn Oauth, start evt. her: 
  * **Google Sign-In OAuth 2.0 Links**
  * [Google Identity Platform](https://developers.google.com/identity)
  * [Google OAuth 2.0](https://developers.google.com/identity/sign-in/web/sign-in)
    - [Google Sign-In Branding Guidelines](https://developers.google.com/identity/branding-guidelines) 
    - [Google Sign-In Samples](https://github.com/GoogleChromeLabs/google-sign-in)
  * [expo-google-sign-in](https://docs.expo.io/versions/latest/sdk/google-sign-in/)
    * [React Native Community Google Sign-In](https://github.com/react-native-community/google-signin)
        - [Guide with React-Native and Expo](https://blog.expo.io/google-sign-in-with-react-native-and-expo-9cac6c392f0e)
  * **What to do if there is a backend involved?**
    - [Eiji Backend Video](https://youtu.be/j_31hJtWjlw) 
    - [API LIBRARIES](https://developers.google.com/api-client-library/)
        - [JavaScript API](https://github.com/google/google-api-javascript-client)
        - [Backend NodeJS API](https://github.com/googleapis/google-api-nodejs-client)
    - [Eiji Authorization Video](https://youtu.be/zZt8SFivjps)
  * [Apollo Authentication](https://www.apollographql.com/docs/apollo-server/security/authentication/)
* [x] Vælg en strategi for implementeringen i backend og i app'en. 
  * [x] Find en god tutorial til Expo React Native App SSO **Authentication** for at få et ID token. 
  * [x] Find en god tutorial til GraphQL Express Backend **Authorization** med et ID token. 
* [x] Hvordan får vi sendt access code til en backend der kan exchange den for et ID token og holde session for vores react-native frontend? Lige nu er der implementeret et implicit flow, og det er ikke særlig godt. Vi vil gerne ende med et Server Flow. 
    - Server Flow: https://developers.google.com/identity/protocols/oauth2/openid-connect#server-flow
    - https://developers.google.com/identity/sign-in/web/backend-auth
    - Passport går tit igen i guides, som fx her: 
        - https://www.freecodecamp.org/news/how-to-nail-social-authentication-in-graphql-27943aee5dce/
        - Så vi kan bede om kun access token i frontend? Og så sende det til backend, som så kontakter google, exchanger access token + client secret for et JWT ID token, som så kan bruges til at lave en login session? 

## Læsemateriale 
Jeg har gået helt forkert til værks. OAuth er ikke engang til at etablere Login Sessions, som er det jeg har prøvet på. No wonder det har været så umuligt. Der skal man bruge **SSO** (Single Sign-On) OIDC ( OPEN ID CONNECT ) som er et lag oven på OAuth 2 til også at sende bruger info, som kan bruges til at lave session login. OAuth sender kun et access token. Med SSO får man OGSÅ et ID Token, som er det vi er interesserede i. 
Man skal starte i frontenden og lave **Authentication** der. Det er den der faktisk laver de der kald til fx GitHub auth osv. 
Så når frontenden har det der authorization code, så kan den sende det til backenden, som så kan anmode om et token, til **Authorization**.

- https://youtu.be/t18YB3xDfXI 
- https://youtu.be/996OiexHze0 

Anbefaler jer at se begge. Sæt 2 timer af til det med en kop te, og noget frugt til at snacke på. Tag en pause undervejs, og se noget af det to gange.

## Terminology 

[Source](https://youtu.be/996OiexHze0)
![Untitled](https://user-images.githubusercontent.com/11192971/82079241-cdef2a80-96e2-11ea-843b-7329a468f289.png)

#### d. 16-05
Prøver nu <https://docs.expo.io/versions/latest/sdk/app-auth/>

Nye forsøg https://github.com/Hold-Krykke/Security_and_FullstackJavascript_Exam/pull/10

#### d. 18-05
Vi har lavet en succesfuld opeid op mod google nu, se https://github.com/Hold-Krykke/Security_and_FullstackJavascript_Exam/pull/12. Vi skal nu håndtere:
- [x] ![#4ba38c](https://via.placeholder.com/15/4ba38c/000000?text=+) `(Camilla)` frontend skal kobles på og skal kunne logge ind via et browserview - Se #14 
  - [x] ![#4ba38c](https://via.placeholder.com/15/4ba38c/000000?text=+) `(Camilla)``  frontend skal håndtere de (endnu ikke-eksisterende) jwt tokens der kommer fra backenden
##### Tegning til frontenden
![image](https://user-images.githubusercontent.com/35559774/82326475-2cffb880-99dd-11ea-9adb-187ca837b5db.png)

- [x] ![#4ba38c](https://via.placeholder.com/15/4ba38c/000000?text=+) `(Camilla)`  vi skal lave en session der er identisk for google og ikke-google brugere (og vi skal kunne tjekke login-status på google-brugere vhja refreshtoken)

### Brugbare links
* https://docs.expo.io/versions/latest/sdk/webview/
* https://stackoverflow.com/questions/51259156/react-native-open-link-in-browser-and-return-to-app?fbclid=IwAR3FD4kq9_OQPKIAMokk2VO2RiDY8tvqbnTEvtkaHA5mcSiaj8kk5D-y_qo
* https://reactnative.dev/docs/linking.html
* https://stackoverflow.com/questions/39099444/react-native-webview-get-url?fbclid=IwAR25TE-F-pONEDpJQGooWDMJj5EQgiiqaAD_hPjy3G5Xmm8plO9pg49UwYQ

**Comment by MalteMagnussen** [comment]
[Google OAuth 2.0](https://developers.google.com/identity/sign-in/web/sign-in)

**Comment by MalteMagnussen** [comment]
### Forkert info til det vi skal bruge det til. Dette er OAuth. Vi er interesserede i SSO. 
_Har ladet det stå her, så vi har det evt ifht rapporten. Så vi har tankerne der er blevet gjort undervejs._

Vi skal bruge OAuth til at beskytte en backend API, så der kun er access fra folk der er authenticated, ikke? Den backend laver vi med NodeJS, Express, GraphQL og Apollo? 

Der er en tutorial her https://medium.com/authpack/easy-google-auth-with-node-js-99ac40b97f4c
Har efterhånden set på en del tutorials, bare for at sammenligne, og et fællestræk, er at man i dem alle skal ind på https://console.developers.google.com/apis/credentials og oprette et nyt projekt og nogen nøgler. 

Havde vi ikke en fælles email? Skal jeg oprette et projekt på den google account? Hvad var dens email, login-info osv? 

Overvejelser: 
1. Hvad vil vi fokusere på at lave OAuth 2.0 login med? 
   - Google (Det stemmer jeg for)
   - LinkedIn
   - Whatever else? (edit og add til listen) 
![image](https://i.imgur.com/3fdXxU9.png?1)

2. Hvad skal der til i BackEnden for at holde på tokens? 
3. Når der er valgt Login type (step 1); Find et FrontEnd Framework til at implementere dette så nemt som muligt. Gerne med tutorial / eksempler. 
4. Remember to do "Incremental Authorization". Only ask for Permissions, when they are needed. 

`"oauth 2.0" "google sign-in" react native frontend "graphql" backend`
Denne [stackoverflow](https://stackoverflow.com/questions/57972116/oauth2-google-authentication-flow-next-js-express) førte mig til [Passport](http://www.passportjs.org/packages/passport-google-oauth20/) Som ser rigtig nice ud. Det stemmer overens med det Eiji fra Google sagde i sin video linked ovenover, siden det håndterer tingene ordentligt og afleverer en user. 

#### Guide / Tutorial
'Developers using the popular Express web framework can refer to an example as a starting point for their own web applications. The example shows how to authenticate users using Facebook. However, because both Facebook and Google use OAuth 2.0, the code is similar. **Simply replace references to Facebook with corresponding references to Google.**'
<https://github.com/passport/express-4.x-facebook-example> 

#### 2 artikler for forståelse
<https://aaronparecki.com/oauth-2-simplified/> og <https://medium.com/@jaaaco/facebook-login-with-react-and-graphql-a128243dc841>  

Det lader til at facebook strategien og Google Oauth 2.0 strategierne er meget ens.

**Comment by MalteMagnussen** [comment]
# SSO FLOW

![image](https://user-images.githubusercontent.com/11192971/81719173-ffff5300-947c-11ea-9546-decec800eaa4.png)
![image](https://user-images.githubusercontent.com/11192971/81719360-4359c180-947d-11ea-95bb-a77bdde069db.png)
![image](https://user-images.githubusercontent.com/11192971/81719477-697f6180-947d-11ea-8b27-ec45005cc5a9.png)

**Comment by MalteMagnussen** [comment]
![image](https://user-images.githubusercontent.com/11192971/81719124-ef4edd00-947c-11ea-8100-d0313afe0d97.png)
