### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/Security_and_FullstackJavascript_Exam#4]
Vælg en løsning i forhold til storage:
* __1. database mulighed:__ 
  * 2 droplets, en til databasen og en til webApp’en, med ssh-tunnel imellem
    * Databasen indeholder 
      * Posts og evt. info knyttet til posts (original poster, evt. comments)
      * Passwords til brugere uden oauth login
    * WebApp droplet er lukket med firewall. App kører kun på https
    * Droplets kan kun ssh’es ind på, ingen password
* __2. database mulighed__
  * Vi bruger mongoDB i stedet for ovenstående i mulighed 1. 
* __3. database mulighed__
  * MongoDB til storage af alt vedrørende selve applicationen
  * mySQL database på en droplet til storage af ikke-oauth passwords og refreshtokens   
  

**TASKS**
* [x] Beskriv overvejelser og argumenter, evt i stikord undervejs, skal bruges i rapporten
* [x] Når der er valgt en løsning skal den implementeres, så opret flere **TASKS** når dette er sket
  * Løsning nr. 3 blev valgt
* [x] Setup MySQL server
* [x] Setup MongoDB

**Comment by MalteMagnussen** [comment]
Jeg synes umiddelbart nummer 1. 

Det er nok bedst ifht Security? At vi viser at vi kan det.

**Comment by MrHardcode** [comment]
Er mest fan a nummer 3. MongoDB ville være nice ift. JS, men vi skal selvfølgelig overveje, hvad der giver bedst mening ift. security

**Comment by Runi-VN** [comment]
3 virker meget omfattende, men foretrækker den. :)

Express med MySQL:  
https://expressjs.com/en/guide/database-integration.html#mysql  
https://github.com/mysqljs/mysql
